collections:
  authors:
    output: true

defaults:
  - scope: 
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

url: "https://zlisch.github.io"
baseurl: ""

plugins: 
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed
